trigger:
  branches:
    include:
    - master
  paths:
    include:
    - src/*.Client/**
    - azure-pipelines.yml

pool:
  vmImage: 'ubuntu-latest'

variables:
  buildConfiguration: 'Release'
  dotNetCoreVersion: 3.0.100
  publishOutputDirectory: 'publish'

steps:
- task: UseDotNet@2
  displayName: 'Install .NET Core SDK, version $(dotNetCoreVersion)'
  inputs:
    version: $(dotNetCoreVersion)
- task: DotNetCoreCLI@2
  displayName: 'Run "dotnet build" with config $(buildConfiguration)'
  inputs:
    command: 'build'
    projects: '**/*.Client/*.fsproj'
    arguments: '--configuration $(buildConfiguration)'
- task: DotNetCoreCLI@2
  displayName: 'Run "dotnet publish" with config $(buildConfiguration)'
  inputs:
    command: 'publish'
    projects: '**/src/*.Client/*.fsproj'
    publishWebProjects: false
    arguments: '--configuration $(buildConfiguration) --output $(Build.SourcesDirectory)/$(publishOutputDirectory)'
    zipAfterPublish: false
- task: CopyFiles@2
  displayName: 'Copy published directory'
  inputs:
    sourceFolder: '$(Build.SourcesDirectory)/$(publishOutputDirectory)'
    contents: '**/dist/**'
    targetFolder: '$(Build.ArtifactStagingDirectory)'
    cleanTargetFolder: true
- task: PublishBuildArtifacts@1
  displayName: 'Publishing build artifacts'

