trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

variables:
  buildConfiguration: 'Release'
  dotNetCoreVersion: 3.0.100
  publishOutputDirectory: 'publish'

steps:
- task: UseDotNet@2
  displayName: 'Install .NET Core SDK, version $(dotNetCoreVersion)'
  inputs:
    version: $(dotNetCoreVersion)
- task: DotNetCoreCLI@2
  displayName: 'Run "dotnet build" with config $(buildConfiguration)'
  inputs:
    command: 'build'
    arguments: '--configuration $(buildConfiguration) $(Build.SourcesDirectory)/src/*.Client'
- task: DotNetCoreCLI@2
  displayName: 'Run "dotnet publish" with config $(buildConfiguration)'
  inputs:
    command: 'publish'
    publishWebProjects: true
    arguments: '--configuration $(buildConfiguration) --output $(Build.SourcesDirectory)/$(publishOutputDirectory)/ $(Build.SourcesDirectory)/src/*.Client'
    zipAfterPublish: false
- task: CopyFiles@2
  displayName: 'Copy published directory'
  inputs:
    sourceFolder: '$(Build.SourcesDirectory)/$(publishOutputDirectory)'
    contents: '**/dist/**'
    targetFolder: '$(Build.ArtifactStagingDirectory)/dist'
    cleanTargetFolder: true
- task: PublishBuildArtifacts@1
  displayName: 'Publishing build artifacts'

